# Generated by Django 4.2 on 2023-04-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripchecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={'verbose_name_plural': 'Trips'},
        ),
        migrations.AddField(
            model_name='trips',
            name='latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
