# Generated by Django 4.2 on 2023-04-28 07:40

from django.db import migrations, models
import tripchecker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tripchecker', '0002_alter_trips_options_trips_latitude_trips_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='name',
            field=models.CharField(max_length=200, validators=[tripchecker.models.validate_name]),
        ),
    ]
