# Generated by Django 4.2 on 2023-04-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripchecker', '0003_alter_trips_latitude_alter_trips_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='visited',
            field=models.CharField(choices=[('Yes', 'No')], default='No', max_length=3),
        ),
    ]
