# Generated by Django 4.2 on 2023-05-03 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tripchecker', '0004_trips_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trips',
            name='visited',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=('N', 'No'), max_length=3),
        ),
    ]
